//todo page
export const GET_TODO_LIST_PROCESS = "GET_TODO_LIST_PROCESS";
export const GET_TODO_LIST = "GET_TODO_LIST";
export const CLEAR_TODO_LIST = "CLEAR_TODO_LIST";
export const UPDATE_TODO_LIST = "UPDATE_TODO_LIST";
export const UPDATE_TODO_LIST_PROCESS = "UPDATE_TODO_LIST_PROCESS";
export const ADD_TODO_ITEM = "ADD_TODO_ITEM";
export const ADD_TODO_ITEM_PROCESS = "ADD_TODO_ITEM_PROCESS";
export const DELETE_TODO_ITEM = "DELETE_TODO_ITEM";
export const DELETE_TODO_ITEM_PROCESS = "DELETE_TODO_ITEM_PROCESS";
export const TODO_LIST_ERROR = "TODO_LIST_ERROR";
export const TODO_LIST_LOADING = "TODO_LIST_LOADING";
export const TODO_CLEAR_ERRORS = "TODO_CLEAR_ERRORS";
